version: '3.5'

services:
  server:
    image: cortezaproject/corteza:${VERSION}
    restart: always
    env_file: [ .env ]
    depends_on: [ db ]
    ports: [ "127.0.0.1:18080:80" ]

  db:
    image: percona:8.0
    restart: always
    volumes: 
      - "dbdata:/var/lib/mysql"
    environment:
      MYSQL_DATABASE: corteza
      MYSQL_USER:     corteza
      MYSQL_PASSWORD: corteza
      # get the random generated password by running: docker-compose logs db | grep "GENERATED ROOT PASSWORD"
      MYSQL_RANDOM_ROOT_PASSWORD: random

    healthcheck: { test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"], timeout: 20s, retries: 10 }

volumes:
  dbdata:
